"""
TrebBaseHighriskLp Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import TrebBaseHighriskLpStrategy
except ImportError:
    from strategy import TrebBaseHighriskLpStrategy

__all__ = [
    "TrebBaseHighriskLpStrategy",
]
